Add Settings Modal
DarkFlorist/bouquet pull request #31
Opened 2023-03-13 22:09 UTC by 0xjimmy

Fixes #27 With modal popup to configure relay RPC, priority fee and how many blocks in future to target inclusion
fixes #4 Correct relay RPC is used, before this I found a bug where it would only use goerli relay even when mainnet selected.

2023-03-16 06:32 UTC, 0xjimmy commented on app/ts/components/Submit.tsx
> +    const relay = `${CORS_PROXY_PREFIX}${appSettings.peek().relayEndpoint}`
Potentially do not need CORS_PROXY, or the one provided in `/ts/constants.ts` should be changed to something else.

2023-03-17 05:27 UTC, MicahZoltu requested changes
Some formatting feedback and questions, I'll leave this for @KillariDev to do a more complete review.

2023-03-17 05:27 UTC, MicahZoltu commented on app/css/index.css
> +.bg-black\/20 {
What is with the escaped `/` here?  Seems like it would be easier to just use a `-` or something that doesn't require escaping.

2023-03-17 05:27 UTC, MicahZoltu commented on app/ts/components/App.tsx
> +  }
Wrong indentation style for repository (see `.editorconfig`).

2023-03-17 05:27 UTC, MicahZoltu commented on app/ts/components/Navbar.tsx
Wrong indentation style for repository.

2023-03-17 05:27 UTC, MicahZoltu commented on app/ts/components/Settings.tsx
> +  }
Indentation wrong.  Start and end of file are correct, I'm not sure how your editor is letting you get away with mixing like this.

2023-03-17 05:27 UTC, MicahZoltu commented on app/ts/components/Submit.tsx
Indentation for this file was correct, but it looks like this PR breaks it as a side effect of other changes.

2023-03-17 05:27 UTC, MicahZoltu commented on app/ts/components/Settings.tsx
> +	) : null
This section looks like it is mixed tabs and spaces, which is causing things to not line up correctly.

2023-03-17 05:27 UTC, MicahZoltu commented on app/css/index.css
> +		var(--tw-backdrop-invert) var(--tw-backdrop-opacity) var(--tw-backdrop-saturate) var(--tw-backdrop-sepia);
No arbitrary newlines and `backdrop-filter` appears to be supported in all browsers so `-webkit-backdrop-filter` shouldn't be used.
```suggestion
	backdrop-filter: var(--tw-backdrop-blur) var(--tw-backdrop-brightness) var(--tw-backdrop-contrast) var(--tw-backdrop-grayscale) var(--tw-backdrop-hue-rotate) var(--tw-backdrop-invert) var(--tw-backdrop-opacity) var(--tw-backdrop-saturate) var(--tw-backdrop-sepia);
```

2023-03-17 05:27 UTC, MicahZoltu commented on app/css/index.css
> +		scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
No arbitrary newlines.
```suggestion
	transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
```

2023-03-19 21:51 UTC, 0xjimmy commented on app/ts/components/Submit.tsx
> +    const relay = `${CORS_PROXY_PREFIX}${appSettings.peek().relayEndpoint}`
I think removing the CORS proxy for now, we have the goerli and mainnet endpoints that work fine. If someone uses a custom relay RPC for now they must provide one that works with CORS.

2023-03-19 21:53 UTC, 0xjimmy commented on app/ts/components/Submit.tsx
> +    const relay = `${CORS_PROXY_PREFIX}${appSettings.peek().relayEndpoint}`
Also was a potential external service that could go down and prevent use of the app.

2023-03-20 05:12 UTC, epheph commented
Could you add a border or more contrasting color? It's a tiny bit disorienting not knowing where the model ends

![Screenshot 2023-03-19 at 22 09 30](https://user-images.githubusercontent.com/361654/226252246-6f37c465-22b5-464a-bee1-1579d160e8c8.png)

2023-03-20 07:56 UTC, KillariDev approved these changes

2023-03-20 07:56 UTC, KillariDev commented on app/ts/components/App.tsx
> +			return defaultValues;
```suggestion
			return defaultValues
```

2023-03-20 07:56 UTC, KillariDev commented on app/ts/components/App.tsx
> +	const defaultValues: AppSettings = { blocksInFuture: 3n, priorityFee: 10n ** 9n * 3n, relayEndpoint: MEV_RELAY_MAINNET };
```suggestion
	const defaultValues: AppSettings = { blocksInFuture: 3n, priorityFee: 10n ** 9n * 3n, relayEndpoint: MEV_RELAY_MAINNET }
```

2023-03-20 07:56 UTC, KillariDev commented on app/ts/components/App.tsx
> +			return defaultValues;
```suggestion
			return defaultValues
```

2023-03-20 07:56 UTC, KillariDev commented on app/ts/components/Settings.tsx
> +			parsedValue = Number(value)
```suggestion
		try {
			const parsedValue = Number(value)
```

2023-03-20 07:56 UTC, KillariDev commented on app/ts/components/Settings.tsx
> +			return
these catch alls should not be used as you might miss useful errors

2023-03-21 05:56 UTC, 0xjimmy commented
> 

![image](https://user-images.githubusercontent.com/52896585/226528733-96c42c0a-a008-4863-b696-01d01d5eae80.png)
Darker background now so contrast should be better

2023-03-21 06:02 UTC, merged