Proxy Support & Set emoji as favicon
DarkFlorist/bouquet pull request #66
Opened 2023-08-26 03:37 UTC by 0xjimmy

Changes favicon to bouquet emoji, Fixes #65 
Adds proxy support, if proxy implementation is verified on Etherscan, Fixes #54

2023-08-26 03:44 UTC, 0xjimmy commented
BNB uses a proxy, you can use it to test by decoding an approval

2023-08-26 08:16 UTC, KillariDev requested changes
we should be parsing the results we are getting from various API's to check that they return what we expect

2023-08-26 08:16 UTC, KillariDev commented on app/ts/components/Transactions.tsx
> +			for (let contract of contracts) {
```suggestion
			for (const contract of contracts) {
```

2023-08-26 08:16 UTC, KillariDev commented on app/ts/components/Transactions.tsx
> +						abis.push(implResult.status === "1" && implResult.result ? implResult.result : undefined)
```suggestion
						abis.push(implResult.status === '1' && implResult.result ? implResult.result : undefined)
```

2023-08-26 08:16 UTC, KillariDev commented on app/ts/components/Transactions.tsx
> +			const contracts = await Promise.all(requests.map((request) => request.json()))
we should be parsing the request that it matches expected type

2023-08-26 08:16 UTC, KillariDev commented on app/ts/components/Transactions.tsx
> +						const implResult = await implReq.json() as { status: '1' | '0', result?: string }
we should be parsing this with funtypes and not assuming its correct

2023-08-28 05:58 UTC, KillariDev approved these changes

2023-08-28 07:03 UTC, merged